### PR TITLE
Add express to badgeboard

### PR DESCRIPTION
**Pull request by styfle**
It seems like adding express to the badgeboard could solve this issue: https://github.com/expressjs/express/pull/3710

### CODE REVIEW

**Comment by dougwilson** [comment]
Oops, sorry I missed this. Yea, express wqs originally left out on purpose, in order for the board to just list the middleware.

I wonder if we can add like a feature to badgeboard to support like grouping instead of just discarding certain projects from the board.

**Comment by styfle** [comment]
Grouping could be nice. But it's a new feature that could be added after this PR lands in my opinion.

**Comment by dougwilson** [comment]
Not really, because ad I said, it was specifically excluded because we didn't want to mix it in with the other middleware. If it was accidentally left our, sure, but it's not missing on accident.

**Comment by dougwilson** [comment]
I will work on adding the feature to badgeboard as soon as I am able and then get this landed.

**Pull request closed without merging**
